routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('posts' , 'PostController', ['middleware' => 'auth']);

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    public $timestamps = false;
    protected $table = 'permissions';
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
	use SoftDeletes;
    public $timestamps = true;
    protected $table = 'posts';

    public function user(){
    	return $this->belongsTo(User::class);
    }

    public function tags(){
    	return $this->hasMany(Tag::class, 'post_id', 'id');
    }
}

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    public $timestamps = false;
    protected $table = 'roles';

    public function permissions()
    {
        return $this->belongsToMany('App\Permission');
    }

    public function hasPermission($perm)
    {
        $user_permissions = $this->permissions
        						->pluck("type")
        						->toArray();

        return in_array($perm, $user_permissions);
    }
}

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public $timestamps = true;
    protected $table = 'tags';
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function permissions()
    {
        return $this->role->permissions->pluck('type')->toArray();
    }
}

app/helper.php
<?php

function generate_slug(){
	
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }


}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Illuminate\Support\Str;

use Auth;
use App\Tag;
use App\Post;

class PostController extends Controller
{
	public function __construct(){
		$this->middleware('can:can_create_post')
				->only(['create' ,'store']);
		$this->middleware('can:can_view_post')
				->only(['index', 'show']);
		$this->middleware('can:can_edit_post')
				->only(['edit' ,'update']);
		$this->middleware('can:can_delete_post')
				->only(['destroy']);
	}
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		// dd(auth()->user()->role->hasPermission("can_delete_post"));
		$posts = Post::orderBy('id', 'desc')->paginate(6);
		return view('post-list', compact('posts'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('add-post');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{   

		$this->validate($request, [
			'title' => 'required',
			'description' => 'required',
			'tags' => 'required',
			'featured_image' => 'required|mimes:jpg,jpeg,png',
		],[
			'title.required' => 'Title of the post is required.',
			'description.required' => 'Description of the post is required.',
			'tags.required' => 'Please enter at least one tag for the post.',
			'featured_image.required' => 'Featured image field is required.',
		]);

		$img_path = '';
		if($request->hasfile('featured_image')){
			$img_path = 'storage/'.$request->file('featured_image')->store('post-imgs/'. date('Y/m/d'));
		}
		// dd($request);
		$str = str_shuffle($request->title).'-'.time();
		
		$post = new Post();
		$post->user_id = Auth::user()->id;
		$post->title = $request->title;
		$post->slug = Str::slug($str);
		$post->description = $request->description;
		if($img_path != null){
			$post->featured_image = $img_path;
		}
		$post->thumbnail_image = $img_path;
		$post->save();

		$tags = explode(' ', $request->tags);
		foreach ($tags as $key => $tag) {
			$query = new Tag();
			$query->user_id = Auth::user()->id;
			$query->post_id = $post->id;
			$query->tag = $tag;
			$query->save();
		}

		return redirect()->route('posts.index')->with('status', 'Post Added successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($slug)
	{
		$post = Post::where('slug', $slug)->with('tags', 'user')->first();
		// dd($post);
		return view('post-show', compact('post'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($slug)
	{
		$post = Post::where('slug', $slug)->with('tags')->first();
		// dd($post);
		return view('post-edit', compact('post'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $slug)
	{
		$this->validate($request, [
			'title' => 'required',
			'description' => 'required',
			'tags' => 'required',
			// 'featured_image' => 'required|mimes:jpg,jpeg,png',
		],[
			'title.required' => 'Title of the post is required.',
			'description.required' => 'Description of the post is required.',
			'tags.required' => 'Please enter at least one tag for the post.',
			// 'featured_image.required' => 'Featured image field is required.',
		]);

		$img_path = '';
		if($request->hasfile('featured_image')){
			$img_path = 'storage/'.$request->file('featured_image')->store('post-imgs/'. date('Y/m/d'));
		}
		// dd($request);
		$str = str_shuffle($request->title).'-'.time();
		
		$post = Post::where('slug', $slug)->first();
		if($post == null){
			return redirect()->back()->with('error', 'Post does not exists.');
		}
		$post->user_id = Auth::user()->id;
		$post->title = $request->title;
		$post->slug = Str::slug($str);
		$post->description = $request->description;
		if($img_path != null){
			$post->featured_image = $img_path;
		}
		$post->thumbnail_image = $img_path;
		$post->save();

		$tags = explode(' ', $request->tags);
		Tag::where('post_id', $post->id)->delete();
		foreach ($tags as $key => $tag) {
			$query = new Tag();
			$query->user_id = Auth::user()->id;
			$query->post_id = $post->id;
			$query->tag = $tag;
			$query->save();
		}

		return redirect()->route('posts.index')->with('status', 'Post updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($slug)
	{
		Post::where('slug', $slug)->delete();
		return redirect()->route('posts.index')->with('status', 'Post deleted successfully.');
	}
}

resources/views/add-post.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Add Post
                </div>

                <div class="card-body">
                    @if(session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger" role="alert">
                                {{$error}}
                            </div>
                        @endforeach
                     @endif
                    <form class="form-horizontal" action="{{ route('posts.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="email">Title:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="email" placeholder="Enter title of post" name="title" value="{{ old('title') }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="pwd">Description:</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" name="description" placeholder="Enter Texts to post">{{old('description')}}</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-6" for="email">Tags (Enter space among tags for multiple):</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="email" placeholder="Enter tags e.g. hello folks" name="tags" value="{{old('tags')}}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-4" for="pwd">Featured Image:</label>
                            <div class="col-sm-10">
                                <input type="file" class="form-control" name="featured_image">
                            </div>
                        </div>
                        <div class="form-group">        
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <a href="{{ route('posts.index') }}" class="btn btn-success">See Post</a>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/post-edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Edit Post
                </div>

                <div class="card-body">
                    @if(session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger" role="alert">
                                {{$error}}
                            </div>
                        @endforeach
                     @endif
                    <form class="form-horizontal" action="{{ route('posts.update', $post->slug) }}" enctype="multipart/form-data" method="POST">
                        @method('PUT')
                        @csrf
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="email">Title:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="email" placeholder="Enter title of post" name="title" value="{{ $post->title }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="pwd">Description:</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" name="description" placeholder="Enter Texts to post">{{ $post->description }}</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-6" for="email">Tags (Enter space among tags for multiple):</label>
                            <div class="col-sm-10">
                                    <?php $tag = ''; ?>
                                    @if($post->tags != null)
                                        @foreach($post->tags as $key => $value)
                                            <?php $tag  = $tag .' '. $value->tag; ?>
                                        @endforeach
                                    @endif
                                <input type="text" class="form-control" id="email" placeholder="Enter tags e.g. hello folks" name="tags" value="{{$tag}}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-4" for="pwd">Featured Image:</label>
                            <div class="col-sm-10">
                                <input type="file" class="form-control" name="featured_image">
                            </div>
                        </div>
                        <div class="form-group">        
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/post-list.blade.php
@extends('layouts.app')
@php
    $user_permissions = auth()->user()->permissions();
@endphp
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    @if(in_array('can_create_post', $user_permissions))
                        <a href="{{ route('posts.create') }}" class="btn btn-success">Add Post </a>
                    @else
                        Post Lists
                    @endif
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>User Name</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Image</th>
                                <th>Thumbnail Image</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                @if(count($posts) > 0)
                                    @foreach($posts as $key => $post)
                                        <td>{{ $loop->index+1 }}</td>
                                        <td>{{ $post->user->name }}</td>
                                        <td>{{ $post->title }}</td>
                                        <td>{{ $post->description }}</td>
                                        <td><a href="{{ asset($post->featured_image) }}" target="_blank">view</a></td>
                                        <td><a href="{{ asset($post->thumbnail_image) }}" target="_blank">view</a></td>
                                        <td>{{ $post->created_at }}</td>
                                        <td>
                                            <div class="dropdown">
                                              <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Action
                                              <span class="caret"></span></button>
                                              <ul class="dropdown-menu">
                                                @if(in_array('can_edit_post', $user_permissions))
                                                    <li><a href="{{ route('posts.edit', $post->slug) }}">Edit Post</a></li>
                                                @endif

                                                @if(in_array('can_delete_post', $user_permissions))
                                                    <li>
                                                        <form action="{{ route('posts.destroy', $post->slug) }}" method="post">
                                                            @method('DELETE')
                                                            @csrf
                                                            <input type="submit" name="submit">
                                                        </form>
                                                    </li>
                                                @endif

                                                @if(in_array('can_view_post', $user_permissions))
                                                    <li><a href="{{ route('posts.show', $post->slug) }}">View Detail</a></li>
                                                @endif
                                              </ul>
                                            </div>
                                        </td>
                                    @endforeach
                                @endif
                            </tr>
                        </tbody>
                    </table>
                    {{$posts->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/post-show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <a href="{{ route('posts.index') }}" class="btn btn-success">See Post</a>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div>Post Owner: {{ $post->user->name }}</div>
                    <div>Post Title: {{ $post->title }}</div>
                    <div>Post Description: {{ $post->description }}</div>
                    <div>Post Created At: {{ $post->created_at }}</div>
                    <div>
                        Post Image:- 
                        <div><img src="{{ asset($post->featured_image) }}" class="rounded float-left" alt="..."></div> 
                    </div><br>
                    <div>
                        Post Thumbnail Image:- 
                        <div><img src="{{ asset($post->thumbnail_image) }}" class="rounded float-left" alt="..."></div> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection